resolver: lts-11.8
flags: {}
packages:
- siggy-chardust
- units
- location:
    git: https://github.com/blockscope/uom-plugin.git
    commit: c170a2df329fe8e40d13aea0b4299758d5079bda
  subdirs:
  - uom-plugin
  extra-dep: true
extra-deps:
- hxt-xpath-9.1.2.2
- liquid-fixpoint-0.7.0.7
- located-base-0.1.1.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
local-bin-path: __shake-build
