resolver: lts-11.8
flags: {}
packages:
- units
- location:
    git: https://github.com/ucsd-progsys/liquidhaskell.git
    commit: 8b783a6d5abda835f2b881aa655b5dd9dfd06d80
  extra-dep: true
extra-deps:
- uom-plugin-0.3.0.0
- hxt-xpath-9.1.2.2
- liquid-fixpoint-0.7.0.7
- located-base-0.1.1.1
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
